# kubectl create -n shoppie-ms secret generic product-catalog-service-secret --from-env-file=.env.prod
# kubectl delete -n shoppie-ms secret product-catalog-service-secret
apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwcm9kdWN0LWNhdGFsb2ctc2VydmljZS1kYi1zdmM6NTQzMi9wcm9kdWN0X2NhdGFsb2dfZGI=
  FLASK_APP: YXBwLnB5
  FLASK_ENV: ZGV2ZWxvcG1lbnQ=
  JWT_SECRET_KEY: eW91cl9zZWNyZXRfa2V5
  MESSAGE_QUEUE_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXN2Yzo1Njcy
  REDIS_HOST: cmVkaXMtc3Zj
  REDIS_PORT: NjM3OQ==
kind: Secret
metadata:
  name: product-catalog-service-secret
  namespace: shoppie-ms