apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: shoppie-ms
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: dhub.pubalibankbd.com/redis/redis:7.2-alpine
        name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: shoppie-ms
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    # nodePort: 30500
    name: redis-port
  selector:
    app: redis
