apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: shoppie-ms
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: dhub.pubalibankbd.com/shoppie_ms/shoppie-payment-service:v1.0.3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: payment-service-secret
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
  namespace: shoppie-ms
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: payment-service
  type: ClusterIP

