apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-db-pv-claim
  namespace: shoppie-ms
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
