# kubectl -n shoppie-ms create secret generic order-db-secret --from-env-file=.env.prod.db
# kubectl -n shoppie-ms delete secret order-db-secret
apiVersion: v1
data:
  POSTGRES_DB: b3JkZXJfZGI=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: order-db-secret
  namespace: shoppie-ms