apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-db-deployment
  namespace: shoppie-ms
spec:
  selector:
    matchLabels:
      app: order-service-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-service-db
    spec:
      containers:
      - image: dhub.pubalibankbd.com/postgres/postgres:17
        name: order-service-db
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: order-db-secret
        ports:
        - containerPort: 5432
          name: pgsql-port
        volumeMounts:
        - name: order-service-db-persistent-storage
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: order-service-db-persistent-storage
        persistentVolumeClaim:
          claimName: order-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-db-svc
  namespace: shoppie-ms
spec:
  ports:
  - port: 5432
  selector:
    app: order-service-db
