# kubectl -n shoppie-ms create secret generic product-catalog-db-secret --from-env-file=.env.prod.db
# kubectl -n shoppie-ms delete secret product-catalog-db-secret
apiVersion: v1
data:
  POSTGRES_DB: cHJvZHVjdF9jYXRhbG9nX2Ri
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: product-catalog-db-secret
  namespace: shoppie-ms