# kubectl create -n shoppie-ms secret generic inventory-app-secret --from-env-file=.env.prod
# kubectl delete -n shoppie-ms secret inventory-app-secret
apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BpbnZlbnRvcnktZGItc3ZjOjU0MzIvaW52ZW50b3J5X2Ri
  FLASK_APP: YXBwLnB5
  FLASK_ENV: ZGV2ZWxvcG1lbnQ=
  JWT_SECRET_KEY: eW91cl9zZWNyZXRfa2V5
  MESSAGE_QUEUE_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXN2Yzo1Njcy
kind: Secret
metadata:
  name: inventory-app-secret
  namespace: shoppie-ms