apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: shoppie-ms
  labels:
    app: auth-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-app
  template:
    metadata:
      labels:
        app: auth-service-app
    spec:
      containers:
      - name: auth-service-app
        image: dhub.pubalibankbd.com/shoppie_ms/shoppie-auth-service:v1.0.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: auth-service-secret
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  namespace: shoppie-ms
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30020
  selector:
    app: auth-service-app
  type: NodePort
