# kubectl create -n shoppie-ms secret generic auth-service-secret --from-env-file=.env.prod --dry-run=client -oyaml
# kubectl delete -n shoppie-ms secret auth-service-secret
apiVersion: v1
data:
  C_TRUSTED_ORIGINS: aHR0cDovL2xvY2FsaG9zdDo4MDAwIGh0dHBzOi8vc2hvcHBpZS1tcy1hdXRoLnB1YmFsaWJhbmtiZC5jb20gaHR0cHM6Ly9zaG9wcGllLW1zLWFwaWd3LnB1YmFsaWJhbmtiZC5jb20=
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BhdXRoLWRiLXN2Yzo1NDMyL2F1dGhfZGI=
  DEBUG: MQ==
  DJANGO_ALLOWED_HOSTS: bG9jYWxob3N0IDEyNy4wLjAuMSBzaG9wcGllLW1zLWF1dGgucHViYWxpYmFua2JkLmNvbSBzaG9wcGllLW1zLWFwaWd3LnB1YmFsaWJhbmtiZC5jb20=
  POSTGRES_DB: YXV0aF9kYg==
  POSTGRES_HOST: YXV0aC1kYi1zdmM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: cG9zdGdyZXM=
  SECRET_KEY: eW91cl9zZWNyZXRfa2V5
kind: Secret
metadata:
  name: auth-service-secret
  namespace: shoppie-ms