# kubectl create -n shoppie-ms secret generic analytics-service-secret --from-env-file=.env.prod
# kubectl delete -n shoppie-ms secret analytics-service-secret
apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BhbmFseXRpY3Mtc2VydmljZS1kYi1zdmM6NTQzMi9hbmFseXRpY3NfZGI=
  JWT_SECRET_KEY: eW91cl9zZWNyZXRfa2V5
  MESSAGE_QUEUE_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXN2Yzo1Njcy
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: shoppie-ms