# kubectl create secret tls api-gateway-tls --key tls.key --cert tls.pem --namespace shoppie-ms
apiVersion: v1
data:
  tls.crt: xxx
  tls.key: yyy
kind: Secret
metadata:
  name: api-gateway-tls
  namespace: shoppie-ms
type: kubernetes.io/tls
