# kubectl create -n shoppie-ms secret generic order-service-secret --from-env-file=.env.prod
# kubectl delete -n shoppie-ms secret order-service-secret
apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BvcmRlci1zZXJ2aWNlLWRiLXN2Yzo1NDMyL29yZGVyX2Ri
  INVENTORY_URL: aHR0cDovL2ludmVudG9yeS1zZXJ2aWNlLXN2Yzo1MDAwL2ludmVudG9yeS1hcGk=
  JWT_SECRET_KEY: eW91cl9zZWNyZXRfa2V5
  MESSAGE_QUEUE_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXN2Yzo1Njcy
kind: Secret
metadata:
  name: order-service-secret
  namespace: shoppie-ms