# kubectl -n shoppie-ms create secret generic rabbitmq-secret --from-env-file=.env.prod.db
apiVersion: v1
data:
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: shoppie-ms