apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: shoppie-ms
spec:
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: dhub.pubalibankbd.com/rabbitmq/rabbitmq:3-management
        name: rabbitmq
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        ports:
        - containerPort: 5672
          name: rmq-port
        - containerPort: 15672
          name: rmq-mgmt-port
        volumeMounts:
        - name: rabbitmq-persistent-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: shoppie-ms
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    # nodePort: 30500
    name: rmq-port
  - port: 15672
    targetPort: 15672
    nodePort: 30023
    name: rmq-mgmt-port
  selector:
    app: rabbitmq
