# kubectl create -n shoppie-ms secret generic shipping-service-secret --from-env-file=.env.prod
# kubectl delete -n shoppie-ms secret shipping-service-secret
apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BzaGlwcGluZy1zZXJ2aWNlLWRiLXN2Yzo1NDMyL3NoaXBwaW5nX2Ri
  JWT_SECRET_KEY: eW91cl9zZWNyZXRfa2V5
  MESSAGE_QUEUE_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXN2Yzo1Njcy
  ORDER_SERVICE_URL: aHR0cDovL29yZGVyLXNlcnZpY2Utc3ZjOjUwMDAvb3JkZXItYXBp
kind: Secret
metadata:
  name: shipping-service-secret
  namespace: shoppie-ms